# SNMP Input
[[inputs.snmp]]
  agents = ["172.20.20.2:161"]
  version = 2c
  community = "public"
  interval = "30s"
  # Define OIDs

# gNMI Input
[[inputs.gnmi]]
  addresses = ["172.20.20.2:50051"]
  username = "admin"
  password = "password"
  [[inputs.gnmi.subscription]]
    origin = "openconfig"
    path = "/interfaces/interface/state/counters"
    subscription_mode = "sample"
    sample_interval = "10s"