!
router bgp 65000
 bgp router-id 10.0.0.100
 no bgp default ipv4-unicast
 
 ! Define the PEs as neighbors
 neighbor 10.0.0.1 remote-as 65000
 neighbor 10.0.0.2 remote-as 65000
 
 ! Activate the VPNv4 Address Family for MPLS L3VPNs
 address-family ipv4 vpn
  neighbor 10.0.0.1 activate
  neighbor 10.0.0.1 route-reflector-client
  neighbor 10.0.0.2 activate
  neighbor 10.0.0.2 route-reflector-client
 exit-address-family
!