neighbor 192.168.11.1 {
    router-id 192.168.11.2;
    local-address 192.168.11.2;
    local-as 65001;
    peer-as 65000;

    static {
        # Injecting two test routes into the PE
        route 10.50.0.0/24 next-hop 192.168.11.2;
        route 10.50.1.0/24 next-hop 192.168.11.2;
    }
}