# Telegraf collection
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000

# Prometheus integration
[[outputs.prometheus_client]]
  listen = ":9273"

# SNMP Input Aristas
[[inputs.snmp]]
  agents = [
    "10.10.10.30:161",  # P1
    "10.10.10.40:161",  # P2
    "10.10.10.50:161",  # P3
    "10.10.10.100:161"  # RR
  ]
  version = 2
  community = "public"
  interval = "30s"
  # Define OIDs
[[inputs.snmp.field]] # hostname as tag to Grafana
    name = "hostname"
    oid = ".1.3.6.1.2.1.1.5.0"
    is_tag = true

  [[inputs.snmp.table]]
    name = "interface"
    inherit_tags = ["hostname"]
    
    [[inputs.snmp.table.field]] # interface name as tag
      name = "ifDescr"
      oid = ".1.3.6.1.2.1.2.2.1.2"
      is_tag = true

    [[inputs.snmp.table.field]] # Up/Down state
      name = "ifOperStatus"
      oid = ".1.3.6.1.2.1.2.2.1.8"

    [[inputs.snmp.table.field]] # inbound Traffic
      name = "ifInOctets"
      oid = ".1.3.6.1.2.1.2.2.1.10"

    [[inputs.snmp.table.field]] # outbound Traffic
      name = "ifOutOctets"
      oid = ".1.3.6.1.2.1.2.2.1.16"

  [[inputs.snmp.field]]
      name = "cpu_utilization_arista"
      oid = "1.3.6.1.4.1.2021.11.11.0" #ssCpuIdle

# SNMP Input Junipers
[[inputs.snmp]]
  agents = [
    "10.10.10.10:161",  # PE1
    "10.10.10.20:161",  # PE2
  ]
  version = 2
  community = "public"
  interval = "30s"
  # Define OIDs
[[inputs.snmp.field]] # hostname as tag to Grafana
    name = "hostname"
    oid = ".1.3.6.1.2.1.1.5.0"
    is_tag = true

  #Interface Traffic and State
  [[inputs.snmp.table]]
    name = "interface"
    inherit_tags = ["hostname"]
    
    [[inputs.snmp.table.field]] # interface name as tag
      name = "ifDescr"
      oid = ".1.3.6.1.2.1.2.2.1.2"
      is_tag = true

    [[inputs.snmp.table.field]] # Up/Down state
      name = "ifOperStatus"
      oid = ".1.3.6.1.2.1.2.2.1.8"

    [[inputs.snmp.table.field]] # inbound Traffic
      name = "ifInOctets"
      oid = ".1.3.6.1.2.1.2.2.1.10"

    [[inputs.snmp.table.field]] # outbound Traffic
      name = "ifOutOctets"
      oid = ".1.3.6.1.2.1.2.2.1.16"

  [[inputs.snmp.field]]
    name = "cpu_utilizationjuniper"
    oid = "1.3.6.1.4.1.2636.3.1.13.1.8.1.1.0" # jnxOperatingCPU for Routing Engine 0


# gNMI Input
[[inputs.gnmi]]
  addresses = [
    "10.10.10.10:32767",  # PE1
    "10.10.10.20:32767",  # PE2
    "10.10.10.30:6030",   # P1
    "10.10.10.40:6030",   # P2
    "10.10.10.50:6030",   # P3
    "10.10.10.100:6030"   # RR
  ]

  username = "admin"
  password = "admin"
  insecure_skip_verify = true
  # sampling
  [[inputs.gnmi.subscription]]
    name = "interfaces_telemetry"
    origin = "openconfig"
    path = "/interfaces/interface/state/counters"
    subscription_mode = "sample"
    sample_interval = "10s"
  # interfaces failures
  # [[inputs.gnmi.subscription]]
  #   name = "interfaces_state"
  #   origin = "openconfig"
  #   path = "/interfaces/interface/state/oper-status"
  #   subscription_mode = "on_change" #immediate