process route-leak {
    run /usr/bin/python3 /run/route_leak.py 200 192.168.11.2 65001 1500000;
    encoder text;
}

neighbor 192.168.11.1 {
    router-id 192.168.11.2;
    local-address 192.168.11.2;
    local-as 65001;
    peer-as 65000;

    static {
        route 10.50.0.0/24 next-hop 192.168.11.2;
    }

    api {
        processes [ route-leak ];
    }
}