process route-flapper {
    run python3 /etc/exabgp/dynamic_routes.py 60 192.168.12.2 65002;
    encoder text;
}

neighbor 192.168.12.1 {
    router-id 192.168.12.2;
    local-address 192.168.12.2;
    local-as 65002;
    peer-as 65000;

    static {
        route 10.60.0.0/24 next-hop 192.168.12.2;
    }

    api {
        processes [ route-flapper ];
    }
}